% gui_resloution.m

clear all
clc
close all


%f1 = figure('Color',[0.95 0.9 0.9],'Name','Diffraction', ...
%     'NumberTitle','off','Position',[20 50 900 600]);
% set(gcf,'units','normalized','position',[0.05 0.05 0.85 0.85]); 
f1 = figure('Color',[0.95 0.9 0.9],'Name','Resolution', ...
     'NumberTitle','off');
% set(gcf,'units','normalized','position',[0.05 0.05 0.85 0.85]); 
set(gcf,'units','normalized') 
set(gcf,'position',[0.01 0.05 0.85 0.85]); 

%t1 = uicontrol(gcf,'Style','text','units','normalized','Position',[0.1 0.7 0.8 0.8], ...
%      'String','Diffraction: Circular Aperture','FontSize',18, ...
%      'HorizontalAlignment','center','FontWeight','bold', ...
%      'BackgroundColor',[0.95 0.9 0.9],'ForegroundColor',[0 0.5 1]);
% t1 = uicontrol(gcf,'Style','text','Position',[250 540 400 30], ...
%      'String','Diffraction: Circular Aperture','FontSize',18, ...
%      'HorizontalAlignment','center','FontWeight','bold', ...
%      'BackgroundColor',[0.95 0.9 0.9],'ForegroundColor',[0 0.5 1]);

%sp1 = subplot('Position',[0 0.8 0.1 0.1]); axis off;
%t1 = text(0,1,'Diffraction: Circular Aperutre','FontName','Arial','FontSize',18, ...
%      'FontWeight','bold');

Text_heading = uicontrol(gcf,'Style','text','units','normalized','Position',[0.2 0.92 0.4 0.05], ...
          'String','LENS - EYE: Focal length 22 mm ','FontSize',14,'HorizontalAlignment','righ', ...
          'BackgroundColor',[0.95 0.9 0.9],'FontWeight','bold', ...
          'ForegroundColor',[0 0.5 1]);

  % Input Initial Data
boxA = 550; boxB = 1; boxC = 3; boxD = -3;   boxE = 22;

%sp2 = subplot('Position',[0 0.6 0.1 0.1]); axis off; box on
fs = 10;
Text_a = uicontrol(gcf,'Style','text','units','normalized','Position',[0.01 0.82 0.4 0.1], ...
          'String','wavelength (400 to 750 nm)  ','FontSize',fs,'HorizontalAlignment','left', ...
          'BackgroundColor',[0.95 0.9 0.9]);
      
Edit_boxA = uicontrol(gcf,'Style','edit','units','normalized','Position',[0.03 0.82 0.055 0.05], ...
        'String',boxA,'FontSize',fs,'BackgroundColor',[1 1 1], ...
        'Callback','boxA = str2num(get(Edit_boxA,''String''));');
      
Text_b = uicontrol(gcf,'Style','text','units','normalized','Position',[0.16 0.82 0.4 0.1], ...
          'String','aperture radius (0.5 to 5 mm)  ','FontSize',fs,'HorizontalAlignment','left', ...
          'BackgroundColor',[0.95 0.9 0.9]);
      
Edit_boxB = uicontrol(gcf,'Style','edit','units','normalized','Position',[0.18 0.82 0.05 0.05], ...
        'String',boxB,'FontSize',fs,'BackgroundColor',[1 1 1], ...
        'Callback','boxB = str2num(get(Edit_boxB,''String''));');
    
Text_c = uicontrol(gcf,'Style','text','units','normalized','Position',[0.32 0.82 0.4 0.1], ...
          'String','source 1 (0 to 8 um)  ','FontSize',fs,'HorizontalAlignment','left', ...
          'BackgroundColor',[0.95 0.9 0.9]);
      
Edit_boxC = uicontrol(gcf,'Style','edit','units','normalized','Position',[0.34 0.82 0.06 0.05], ...
        'String',boxC,'FontSize',fs,'BackgroundColor',[1 1 1], ...
        'Callback','boxC = str2num(get(Edit_boxC,''String''));');    
    
Text_d = uicontrol(gcf,'Style','text','units','normalized','Position',[0.45 0.82 0.4 0.1], ...
          'String','source 2 (-8 to um) ','FontSize',fs,'HorizontalAlignment','left', ...
          'BackgroundColor',[0.95 0.9 0.9]);
      
Edit_boxD = uicontrol(gcf,'Style','edit','units','normalized','Position',[0.47 0.82 0.06 0.05], ...
        'String',boxD,'FontSize',fs,'BackgroundColor',[1 1 1], ...
        'Callback','boxD = str2num(get(Edit_boxD,''String''));');    

Text_e = uicontrol(gcf,'Style','text','units','normalized','Position',[0.6 0.82 0.4 0.1], ...
          'String','aperture / screen distance (10 to 100 mm) ','FontSize',fs,'HorizontalAlignment','left', ...
          'BackgroundColor',[0.95 0.9 0.9]);
      
Edit_boxE = uicontrol(gcf,'Style','edit','units','normalized','Position',[0.62 0.82 0.05 0.05], ...
        'String',boxE,'FontSize',fs,'BackgroundColor',[1 1 1], ...
        'Callback','boxE = str2num(get(Edit_boxE,''String''));');        
    
pushbutton_run = uicontrol(gcf,'Style','pushbutton','units','normalized','Position',...
     [0.7 0.93 0.05 0.05], 'FontSize',12,'FontWeight','bold', 'String','RUN', ...
     'CallBack', 'gui_resolution_cal');
 
 
 pushbutton_close = uicontrol(gcf,'Style','pushbutton','units','normalized','Position',...
     [0.8 0.93 0.05 0.05], 'FontSize',12,'FontWeight','bold', 'String','CLOSE', ...
     'CallBack', 'close');
 
 
 
      